apiVersion: v1
kind: ConfigMap
metadata:
  name: api-secret-credentials
  labels:
    app: sevenfood-api
data:
  DATABASE_URL: jdbc:postgresql://rds-sevenfood.crcs2uugubni.us-east-1.rds.amazonaws.com:5432/sevenfood
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: Postgres2019!

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevenfood-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sevenfood-api
  template:
    metadata:
      labels:
        app: sevenfood-api
    spec:
      containers:
        - name: sevenfood-api-container
          image: marrani/sevenfood-api:latest
          ports:
            - containerPort: 9991
          envFrom:
            - configMapRef:
                name: api-secret-credentials
