name: CI/CD para AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2

      - name: Configurar AWS CLI e contexto do cluster EKS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: marrani/sevenfood-api:latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name sevenfood-eks

      - name: Implantação da API no Cluster EKS
        run: |
          kubectl apply -f infra/k8s/api/ -n postech-soat
        working-directory: ${{ github.workspace }}